# baseURL = "https://example.edu"
# baseURL = "https://www.stats.ox.ac.uk/~bzhang/"
baseURL = "https://resonant-licorice-2ad61b.netlify.app"
languageCode = "en-us"
title = "Brian C. Zhang"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "PhD"
  interests="Statistical Genetics, Population Genetics, Machine Learning"
  # cv_name= "HadiSinaee_CV.pdf"
  blog="https://brianzhang01.github.io/"

[[params.affilation]]
  name = "University of Oxford"
  position = "PhD"
  contact = "brian.zhang@well.ox.ac.uk"

# [[params.affilation]]
#  name = "MyCoolStartup"
#  position = "Co-Founder"
#  contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/brianzhang01"

[[params.social]]
  name = "Google Scholar"
  icon = "book-open"
  url = "https://scholar.google.com/citations?user=zJPPrfkAAAAJ"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/brianczhang"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/brianzhang01/"

[[params.introduction.paragraph]]
  text="""I defended my PhD in 2022 and am now working as a computational biologist at Adaptive Biotechnologies!
   """

[[params.introduction.paragraph]]
  text="""At Oxford, I was a member of [Pier Palamara's group](https://palamaralab.github.io/). We developed a method, ARG-Needle, to infer the genome-wide genealogy of a set of genetic samples from genotyping array or sequencing data. We built the genome-wide genealogy of 337K samples in the UK Biobank and scanned the genealogy for associations with 7 complex traits. This yielded more rare and ultra-rare associations than found by genotype imputation, which were overall enriched for loss-of-function variation. View my thesis [here](brian_thesis.pdf).
   """

[[params.introduction.paragraph]]
  text="""During my PhD, I was supported by the Clarendon Scholarship and was a member of St. John's College. Before Oxford, I worked for two years as a research engineer at DeepMind in London.
   """

[[params.projects]]
	[[params.projects.project]]
		name = "Biobank-Scale Ancestral Recombination Graph Inference"
		description  = "In population genetics, the ancestral recombination graph (ARG) captures the history of coalescence, recombination, and mutation events that gives rise to observed genetic data. We developed a method, ARG-Needle, that leverages coalescent modeling for ascertained genotyping array data to infer accurate, biobank-scale ARGs from SNP arrays. We also developed a framework for performing mixed-model association of unobserved variation implied by an inferred ARG. Using these methods, we inferred the ARG of 337,464 individuals in the UK Biobank and performed genealogy-based association of 7 complex traits, recapitulating as well as detecting complementary associations compared to reference-based imputation. As these methods only require SNP array data, we anticipate they will be particularly relevant for populations that are currently undersequenced."
		project_page = "https://www.biorxiv.org/content/10.1101/2021.11.03.466843"
		code_link = ""
		blog_link = ""

 [[params.projects.project]]
		name = "Mathematics of Linear Mixed Models"
		description  = "My first PhD project focused on improving linear mixed model association in genetics. Standard inference under the mixed model does not scale to modern genetic datasets, so my PhD supervisors and I were looking to build on past methods like BOLT-LMM and LDpred to further improve the scalability of mixed model association. Although I have put the project on pause, my work in this area led me to write a set of expository notes on the mathematics of linear mixed models. (In progress, last modified February 2020.)"
		project_page = "lmm-math.pdf"
		code_link = ""
		blog_link = ""

 [[params.projects.project]]
        name = "Coconuts and Islanders: A Statistics-First Guide to the Boltzmann Distribution"
        description  = "An arXiv writeup presenting the Boltzmann distribution in what I hope is an accessible and intuitive way. I learned this approach from my father and the notes are dedicated to his memory."
        project_page = "https://arxiv.org/abs/1904.04669"
        blog_link = ""

 [[params.projects.project]]
		name = "Random Graphs and Giant Components"
		description  = "An R Markdown blog post introducing the Erdős-Rényi random graph and giant component. I tried to build intuition through figures and animations, but have also linked to further reading on random graphs. Done in my free time during my PhD."
		project_page = "https://brianzhang01.github.io/2018/07/random-graphs-and-giant-components/"
        code_link = "https://github.com/brianzhang01/giant_demo"
		blog_link = ""

[[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Biobank-scale inference of ancestral recombination graphs enables genealogy-based mixed model association of complex traits"
    authors = "__Brian C. Zhang__, Arjun Biddanda, and Pier Francesco Palamara"
    dest  = "bioRxiv 2021"
    link = "https://www.biorxiv.org/content/10.1101/2021.11.03.466843"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "Coconuts and Islanders: A Statistics-First Guide to the Boltzmann Distribution"
    authors = "__Brian Zhang__"
    dest  = "arXiv 2019"
    link = "https://arxiv.org/abs/1904.04669"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "The Kinetics Human Action Video Dataset"
    authors = "Will Kay, João Carreira, Karen Simonyan, __Brian Zhang__, Chloe Hillier, Sudheendra Vijayanarasimhan, Fabio Viola, Tim Green, Trevor Back, Paul Natsev, Mustafa Suleyman, Andrew Zisserman"
    dest  = "arXiv 2017"
    link = "https://arxiv.org/abs/1705.06950"
    code_link = ""
    blog_link = ""

[[params.publications]]
  year="2018"

  [[params.publications.paper]]
		name = "Vector-based navigation using grid-like representations in artificial agents"
		authors = "Andrea Banino, Caswell Barry, Benigno Uria, Charles Blundell, Timothy Lillicrap, Piotr Mirowski, Alexander Pritzel, Martin Chadwick, Thomas Degris, Joseph Modayil, Greg Wayne, Hubert Soyer, Fabio Viola, __Brian Zhang__, Ross Goroshin, Neil Rabinowitz, Razvan Pascanu, Charlie Beattie, Stig Petersen, Amir Sadik, Stephen Gaffney, Helen King, Koray Kavukcuoglu, Demis Hassabis, Raia Hadsell, Dharshan Kumaran"
		dest  = "Nature"
		link = "https://www.nature.com/articles/s41586-018-0102-6.epdf?author_access_token=BjM-5BdGxd14c17YFA6PsdRgN0jAjWel9jnR3ZoTv0OEfySMT4t78PpPpCS7uExW3njb8Q4UlgcwRM32WwBCKZs73SThwkfI42wHhFEtJM-Y7sQxDsR1cR7_C9Kq1GwuxGJn46kzRnujvrDMGzc4TQ%3D%3D"
		code_link = ""
		blog_link = "https://deepmind.com/blog/article/grid-cells"

[[params.publications]]
  year="D.Phil. Thesis"

  [[params.publications.paper]]
    name = "Biobank-Scale Ancestral Recombination Graphs: Inference and Applications to the Analysis of Complex Traits"
    dest  = "University of Oxford, Department of Statistics"
    authors = "__Brian C. Zhang__"
    link = "brian_thesis.pdf"
    code_link = ""
    blog_link = ""
