# baseURL = "https://example.edu"
baseURL = "http://www.stats.ox.ac.uk/~bzhang/"
languageCode = "en-us"
title = "Brian Zhang"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "PhD Student"
  interests="Population Genetics, Machine Learning"
  # cv_name= "HadiSinaee_CV.pdf"
  blog="https://brianzhang01.github.io/"

[[params.affilation]]
  name = "Oxford University"
  position = "PhD Student"
  contact = "brian.zhang@stats.ox.ac.uk"

# [[params.affilation]]
#  name = "MyCoolStartup"
#  position = "Co-Founder"
#  contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/brianzhang01"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/brianczhang"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/brianzhang01/"

[[params.introduction.paragraph]]
  text="""This page about me is a work in progress. I am fortunate to be a member of [Pier Palamara's group](https://www.palamaralab.org) at Oxford.
   """

[[params.introduction.paragraph]]
  text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	 Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Integer feugiat scelerisque varius morbi enim.
	  A diam maecenas sed enim ut sem viverra. Orci eu lobortis elementum nibh tellus.
		Egestas sed sed risus pretium quam vulputate dignissim suspendisse in.
		Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Condimentum lacinia quis vel eros donec.
   """

[[params.projects]]
	[[params.projects.project]]
		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = "https://ablogpost.com"

 [[params.projects.project]]
		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = ""

 [[params.projects.project]]
		name = "Integer eget aliquet nibh praesent tristique magna"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = ""
		blog_link = "https://ablogpost.com"

[[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
    dest  = "Helga Zita Journal"
    link = "https://mypaperishere.com"
    code_link = "https://thecoderepo.com"
    blog_link = "https://myblogaboutit.com"

  [[params.publications.paper]]
    name = "In cursus turpis massa tincidunt dui ut ornare lectus sit"
    authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
    dest  = "Meklit Katlego Conference"
    link = "https://mypaperishere.com"
    code_link = "https://thecoderepo.com"
    blog_link = "https://myblogaboutit.com"

[[params.publications]]
  year="2019"

  [[params.publications.paper]]
		name = "Feugiat sed lectus vestibulum mattis ullamcorper velit sed"
		authors = "Caroll Comes, __Hadi Sinaee__"
		dest  = "Udo Madhu Journal"
		link = "https://mypaperishere.com"
		code_link = "https://thecoderepo.com"
		blog_link = ""

  [[params.publications.paper]]
		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
		dest  = "Zorka Vita Conference"
		link = "https://mypaperishere.com"
		code_link = ""
		blog_link = "https://myblogaboutit.com"

  [[params.publications.paper]]
		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
		dest  = "Lena Randa Conference"
		link = "https://mypaperishere.com"
		code_link = ""
		blog_link = ""

  [[params.publications.paper]]
		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
		authors = "__Hadi Sinaee__, Caroll Comes"
		dest  = "Thandeka Radhika Conference"
		link = ""
		code_link = ""
		blog_link = ""
